language: java
dist: bionic

jdk:
  - openjdk8
  - openjdk11

services:
    - docker

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img

install:
  - mvn clean package

before_script:
  - docker cp ./target/*.xar exist-ci:exist/autodeploy
  - docker start exist-ci
  # exist needs time
  - sleep 30
  - docker ps

script:
  - mvn test
  # TODO
  # - npx cypress run